[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmd = 'npm install --production=false'

[phases.build]
cmd = 'npm run build -- --no-optimization'

[start]
cmd = 'npm run start'

[variables]
NPM_CONFIG_FUND = 'false'
NPM_CONFIG_AUDIT = 'false'
NODE_ENV = 'production'
STRAPI_DISABLE_UPDATE_NOTIFICATION = 'true'
STRAPI_TELEMETRY_DISABLED = 'true'